"""add new model

Revision ID: 5975145d0776
Revises: e4b7e8c165c1
Create Date: 2025-09-22 13:42:49.102236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5975145d0776'
down_revision: Union[str, None] = 'e4b7e8c165c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_inserts',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        "TIMEZONE('utc', now())"), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.alter_column('users', 'word_count',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    existing_server_default=sa.text('5'))
    op.alter_column('users', 'schedule',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    existing_server_default=sa.text('5'))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'schedule',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    existing_server_default=sa.text('5'))
    op.alter_column('users', 'word_count',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    existing_server_default=sa.text('5'))
    op.drop_table('text_inserts')
    # ### end Alembic commands ###
