name: Automerge Dependabot PRs

on:
  workflow_run:
    workflows: [Linting]
    types: [completed]

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_GITHUB_ACCESS_TOKEN }}
    timeout-minutes: 5
